package com.jiat.ndcamera.entity;

public enum MessageType {
    SUCCESS,ERROR,NOT_FOUND,CURRENT_PW_NOT_MATCH,NEW_PW_NOT_MATCH,ALREADY_EXIST,EMAIL_ALREADY_EXIST,CONTACT_NUMBER_ALREADY_EXIST,INVALID
}
